// todo-react-vue/vue-todo/src/App.vue
<template>
  <div id="app">
    <h2 class="text-center">Vue Todos App</h2>
    <input
          type="text"
          name="todo"
          class="form-control"
          placeholder="Add a new todo"
          v-model="newTodo"
    >
    <button
      :disabled="newTodo.length < 1"
      @click="edit ? modifyTodo() : addTodo()"
      class="btn btn-success"
    >
      {{ edit ? 'Update Todo' : 'Add Todo' }}
    </button>
    <ul class="list-group">
      <li
        class="list-group-item list-group-item-info"
        v-for="(todo, index) in todos"
        v-bind:key="todo.id"
    >
      {{ todo.name }}
      <button
        @click="updateTodo(index)"
        class="btn btn-primary"
      >
        Update Todo
      </button>
      <button
        @click="removeTodo(index)"
        class="btn btn-danger"
      >
        Remove Todo
      </button>
    </li>
    </ul>
  </div>
</template>

<script>
export default {
  data() {
    return {
      newTodo: '',
      edit: false,
      index: null,
      todos: [
        {
          id: 1,
          name: 'todo1'
        },
        {
          id: 2,
          name: 'todo2'
        },
        {
          id: 3,
          name: 'todo3'
        }
      ]
    }
  },
  methods: {
    addTodo() {
      const newTodo = {
        id: Date.now(),
        name: this.newTodo
      }
      const todos = this.todos
      todos.push(newTodo)
      this.newTodo = ''
    },
    removeTodo(index) {
      this.todos.splice(index, 1)
    },
    updateTodo(index) {
    const todo = this.todos[index]
      this.edit = true
      this.index = index
      this.newTodo = todo.name
    },
    modifyTodo() {
      const todo = this.todos[this.index]
      todo.name = this.newTodo

      const modifiedTodo = this.todos
      modifiedTodo[this.index] = todo
      this.edit = false
      this.newTodo = ''
      this.index = null
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// todo-react-vue/react-todo/src/App.js
import React, { Component } from 'react';
import './App.css';

class App extends Component {
  constructor() {
    super()
    this.state = {
      newTodo: '',
      index: null,
      todos: [
        {
          id: 1,
          name: 'todo1'
        },
        {
          id: 2,
          name: 'todo2'
        },
        {
          id: 3,
          name: 'todo3'
        }
      ]
    }
    this.handleChange = this.handleChange.bind(this)

    addTodo() {
      const newTodo = {
        id: Date.now(),
        name: this.state.newTodo
      }
      const todos = this.state.todos
      todos.push(newTodo)
      this.setState({
        todos: todos,
        newTodo: '',
        edit: false
      })
    }

    removeTodo(index) {
      const todos = this.state.todos
      todos.splice(index, 1)

      this.setState({
        todos: todos
      })
    }

    updateTodo(index) {
      const todo = this.state.todos[index]
      this.setState({
        edit: true,
        newTodo: todo.name,
        index: index
      })
    }

    modifyTodo() {
      const todo = this.state.todos[this.state.index]
      todo.name = this.state.newTodo

      const modifiedTodo = this.state.todos
      modifiedTodo[this.state.index] = todo
      this.setState({
        todos: modifiedTodo,
        edit: false,
        newTodo: '',
        index: null
      })
    }
  }

  handleChange(e) {
    this.setState({
      newTodo: e.target.value
    })
  }

  render() {
    return (
      <div className="App">
        <h2 className="text-center">React Todos App</h2>
        <input
          type="text"
          name="todo"
          className="form-control"
          placeholder="Add a new todo"
          onChange={this.handleChange}
          value={this.state.newTodo}
        />
        <button
          disabled={this.state.newTodo.length < 1}
          className="btn btn-success"
          onClick={this.state.edit ? this.modifyTodo : this.addTodo}
        >
          {this.state.edit ? 'Update Todo' : 'Add Todo'}
        </button>
        <ul className="list-group">
          {this.state.todos.map((todo, index) => {
            return <li
                      key={todo.id}
                      className="list-group-item list-group-item-info"
                    >
                      {todo.name}
                      <button
                        className="btn btn-primary"
                        onClick={() => this.updateTodo(index)}
                      >
                        Update Todo
                      </button>
                      <button
                        className="btn btn-danger"
                        onClick={() => this.removeTodo(index)}
                      >
                        Remove Todo
                        </button>
                    </li>
          })}
        </ul>
      </div>
    )
  }
}

export default App;
